const assert = require('assert');
const { obfuscate } = require('../src/obfuscator');
const source = 'local value = 42\nprint(value)\n';
const result = obfuscate(source, { level: 1, seed: 7 });
assert(result.code.includes('tonumber('));
const encoded = obfuscate(source, { base64: true, seed: 7 });
assert(encoded.code.includes('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'));
const encrypted = obfuscate(source, { encrypt: true, key: 7, seed: 7 });
assert(encrypted.code.includes('local __key=7'));
const vm = obfuscate(source, { vm: true, seed: 7 });
assert(vm.code.includes('VM dispatcher mode (experimental)'));
console.log('obfuscator tests passed');
