'use strict';

const DEFAULT_BLACKLIST = new Set([
  '_G', '_ENV', 'self', 'game', 'workspace', 'script', 'Instance', 'Vector3',
  'Vector2', 'CFrame', 'Color3', 'UDim2', 'Enum', 'task', 'wait', 'spawn',
  'pcall', 'xpcall', 'require', 'shared', 'coroutine', 'math', 'string', 'table',
  'select', 'tonumber', 'tostring', 'type', 'pairs', 'ipairs', 'next', 'print',
  'warn', 'error', 'assert', 'load', 'loadstring', 'unpack', 'setmetatable',
  'getmetatable', 'rawget', 'rawset', 'true', 'false', 'nil', 'and', 'or', 'not',
  'local', 'function', 'end', 'if', 'then', 'else', 'elseif', 'for', 'while',
  'do', 'repeat', 'until', 'return', 'break'
]);

function lex(source) {
  const tokens = [];
  let i = 0;
  while (i < source.length) {
    const c = source[i];
    if (/\s/.test(c)) {
      let j = i + 1;
      while (j < source.length && /\s/.test(source[j])) j++;
      tokens.push({ type: 'ws', value: source.slice(i, j) }); i = j; continue;
    }
    if (source.startsWith('--', i)) {
      const j = source.indexOf('\n', i);
      const end = j < 0 ? source.length : j;
      tokens.push({ type: 'comment', value: source.slice(i, end) }); i = end; continue;
    }
    if (c === '"' || c === "'") {
      const quote = c; let j = i + 1;
      while (j < source.length) { if (source[j] === '\\') j += 2; else if (source[j++] === quote) break; }
      tokens.push({ type: 'string', value: source.slice(i, j) }); i = j; continue;
    }
    if (c === '[' && source[i + 1] === '[') {
      const endIndex = source.indexOf(']]', i + 2);
      const end = endIndex < 0 ? source.length : endIndex + 2;
      tokens.push({ type: 'string', value: source.slice(i, end) }); i = end; continue;
    }
    const number = source.slice(i).match(/^(?:0[xX][0-9a-fA-F]+|(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)/);
    if (number) { tokens.push({ type: 'number', value: number[0] }); i += number[0].length; continue; }
    const ident = source.slice(i).match(/^[A-Za-z_][A-Za-z0-9_]*/);
    if (ident) { tokens.push({ type: 'ident', value: ident[0] }); i += ident[0].length; continue; }
    const op = source.slice(i).match(/^(?:\.\.\.|::|==|~=|<=|>=|<<|>>|\/\/|\+=|-=|\*=|\/=|\.\.)/);
    if (op) { tokens.push({ type: 'punct', value: op[0] }); i += op[0].length; continue; }
    tokens.push({ type: 'punct', value: c }); i++;
  }
  return tokens;
}

function makeRng(seed) {
  let x = (Number(seed) >>> 0) || 0x9e3779b9;
  return () => ((x = (Math.imul(x ^ (x >>> 16), 2246822507) + 3266489909) >>> 0));
}

function encodedNumber(value) {
  const bytes = Buffer.from(String(value)).map(String).join(',');
  return `tonumber(string.char(${bytes}))`;
}

function encodeString(value) {
  const bytes = Buffer.from(value, 'utf8').map(String).join(',');
  return bytes ? `string.char(${bytes})` : '""';
}

function pack(source) {
  const payload = JSON.stringify(source);
  return `-- generated by Razer Obfuscator\nlocal __load = loadstring or load\nlocal __fn = assert(__load(${payload}))\nreturn __fn()`;
}

function obfuscate(source, options = {}) {
  const level = Math.max(1, Math.min(3, Number(options.level || 1)));
  const rename = options.rename ?? level >= 1;
  const constants = options.constants ?? level >= 1;
  const strings = options.strings ?? level >= 2;
  const packOutput = options.pack ?? level >= 2;
  const standalone = Boolean(options.standalone);
  const blacklist = new Set(DEFAULT_BLACKLIST);
  for (const item of options.blacklist || []) if (item && item.trim()) blacklist.add(item.trim());
  const tokens = lex(source);
  const rng = makeRng(options.seed == null ? Date.now() : options.seed);
  const names = new Map(); const used = new Set(); let declaration = false; let renamed = 0;
  const nextName = () => { let n; do n = `_${(rng() % 0xffffff).toString(36)}`; while (blacklist.has(n) || used.has(n)); used.add(n); return n; };
  for (const token of tokens) {
    if (token.type === 'ident' && token.value === 'local') { declaration = true; continue; }
    if (token.type !== 'ident' || blacklist.has(token.value)) continue;
    if (declaration && !names.has(token.value)) names.set(token.value, nextName());
    if (rename && names.has(token.value)) { token.value = names.get(token.value); renamed++; }
    if (declaration) declaration = false;
  }
  let code = tokens.map((token) => {
    if (token.type === 'number' && constants && !/^0[xX]/.test(token.value)) return encodedNumber(token.value);
    if (token.type === 'string' && strings && token.value[0] !== '[') return encodeString(token.value.slice(1, -1));
    return token.value;
  }).join('');
  if (standalone) code = `-- Razer standalone output\n${code}`;
  else if (packOutput) code = pack(code);
  return { code, stats: { tokens: tokens.length, renamed } };
}

module.exports = { DEFAULT_BLACKLIST, lex, obfuscate, pack };
