'use strict';

// This is deliberately a lexer rather than a regexp pass. It understands Lua
// comments, quoted strings, long strings, numbers, and identifiers, so source
// text inside strings/comments is never modified.
const DEFAULT_BLACKLIST = new Set([
  '_G', '_ENV', 'self', 'game', 'workspace', 'script', 'Instance', 'Vector3',
  'Vector2', 'CFrame', 'Color3', 'UDim2', 'Enum', 'task', 'wait', 'spawn',
  'pcall', 'xpcall', 'require', 'getgenv', 'shared', 'coroutine', 'math',
  'string', 'table', 'select', 'tonumber', 'tostring', 'type', 'pairs',
  'ipairs', 'next', 'print', 'warn', 'error', 'assert', 'load', 'loadstring',
  'unpack', 'setmetatable', 'getmetatable', 'rawget', 'rawset', 'true', 'false',
  'nil', 'and', 'or', 'not', 'local', 'function', 'end', 'if', 'then', 'else',
  'elseif', 'for', 'while', 'do', 'repeat', 'until', 'return', 'break',
]);

function lex(source) {
  const out = [];
  let i = 0;
  const push = (type, value) => out.push({ type, value });
  while (i < source.length) {
    const c = source[i];
    if (/\s/.test(c)) { let j = i + 1; while (j < source.length && /\s/.test(source[j])) j++; push('ws', source.slice(i, j)); i = j; continue; }
    if (source.startsWith('--', i)) {
      const long = source[i + 2] === '[';
      if (long) { const close = source.indexOf(']', i + 3); if (close >= 0) { const j = close + 1; push('comment', source.slice(i, j)); i = j; continue; } }
      const j = source.indexOf('\n', i); push('comment', source.slice(i, j < 0 ? source.length : j)); i = j < 0 ? source.length : j; continue;
    }
    if (c === '"' || c === "'") { const quote = c; let j = i + 1; while (j < source.length) { if (source[j] === '\\') j += 2; else if (source[j++] === quote) break; } push('string', source.slice(i, j)); i = j; continue; }
    if (c === '[' && source[i + 1] === '[') { const j = source.indexOf(']]', i + 2); const end = j < 0 ? source.length : j + 2; push('string', source.slice(i, end)); i = end; continue; }
    const number = source.slice(i).match(/^(?:0[xX][0-9a-fA-F]+|(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)/);
    if (number) { push('number', number[0]); i += number[0].length; continue; }
    const ident = source.slice(i).match(/^[A-Za-z_][A-Za-z0-9_]*/);
    if (ident) { push('ident', ident[0]); i += ident[0].length; continue; }
    const op = source.slice(i).match(/^(?:\.\.\.|::|==|~=|<=|>=|<<|>>|\/\/|\+=|-=|\*=|\/=|\.\.)/);
    if (op) { push('punct', op[0]); i += op[0].length; continue; }
    push('punct', c); i++;
  }
  return out;
}

function makeRng(seed) { let x = (seed >>> 0) || 0x9e3779b9; return () => ((x = Math.imul(x ^ (x >>> 16), 2246822507) + 3266489909) >>> 0); }
function encodedNumber(value, rng) {
  // Runtime parsing prevents Lua's front-end from folding the literal.
  const text = String(value);
  const bytes = [...Buffer.from(text)].map((b) => String(b)).join(',');
  return `tonumber(string.char(${bytes}))`;
}
function pack(source) {
  const bytes = Buffer.from(source, 'utf8');
  let payload = '';
  for (const byte of bytes) payload += `\\${String(byte).padStart(3, '0')}`;
  const chunks = [];
  for (let i = 0; i < payload.length; i += 900) chunks.push(JSON.stringify(payload.slice(i, i + 900)));
  return `-- generated by roblox-lua-obfuscator\nlocal __payload = ${chunks.join(' .. ')}\nlocal __load = loadstring or load\nlocal __chunk, __error = __load(__payload)\nif not __chunk then error(__error) end\nreturn __chunk()`;
}

function obfuscate(source, options = {}) {
  const level = Math.max(1, Math.min(3, options.level || 1));
  const doRename = options.rename ?? level >= 1;
  const doConstants = options.constants ?? level >= 1;
  const doPack = options.pack ?? level >= 2;
  const blacklist = new Set(DEFAULT_BLACKLIST);
  for (const item of (options.blacklist || [])) if (item && item.trim()) blacklist.add(item.trim());
  const tokens = lex(source);
  const rng = makeRng(options.seed == null ? Date.now() : options.seed);
  const names = new Map();
  let renamed = 0;
  let declaration = false;
  let parameterList = false;
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i];
    if (t.type === 'ident' && t.value === 'local') { declaration = true; continue; }
    if (t.type === 'ident' && t.value === 'function') { parameterList = false; continue; }
    if (t.value === '(' && i && tokens[i - 1].type === 'ident') parameterList = true;
    if (t.value === ')' && parameterList) parameterList = false;
    if (t.type !== 'ident' || blacklist.has(t.value)) continue;
    const isDecl = declaration || parameterList;
    if (doRename && isDecl && !names.has(t.value)) {
      let candidate; do { candidate = `_${(rng() % 0xffffff).toString(36)}`; } while (blacklist.has(candidate) || [...names.values()].includes(candidate));
      names.set(t.value, candidate);
    }
    if (doRename && names.has(t.value)) { t.value = names.get(t.value); renamed++; }
    if (declaration && t.value !== ',') declaration = false;
  }
  let code = tokens.map((t) => t.type === 'number' && doConstants && !/^0[xX]/.test(t.value) ? encodedNumber(t.value, rng) : t.value).join('');
  if (doPack) code = pack(code);
  return { code, stats: { tokens: tokens.length, renamed } };
}

module.exports = { lex, obfuscate, DEFAULT_BLACKLIST };
